---
- name: Delete Docker container {{ dkr_container }}
  become: yes
  docker_container:
    name:  "{{ item.key }}"
    image: "{{ dkr_image }}"
    state: absent
    force_kill: true
  with_dict: "{{ host_list }}"
...