---
- name: Converge
  hosts: all
  vars:
    host_type: "docker"
  pre_tasks:
    - name: Install pre-requisites
      include_tasks: "pre_requisites.yml"
  roles:
    - { role: docker_manage_hosts, taskname: "start_host", when: host_type == "docker" }
    - { role: docker_manage_hosts, taskname: "delete_host" }
...
